// @generated by protoc-gen-connect-query v2.0.1 with parameter "target=ts"
// @generated from file api/dashboard.proto (package api, syntax proto3)
/* eslint-disable */

import { DashboardService } from "./dashboard_pb";

/**
 * @generated from rpc api.DashboardService.CreateDashboard
 */
export const createDashboard = DashboardService.method.createDashboard;

/**
 * @generated from rpc api.DashboardService.GetDashboards
 */
export const getDashboards = DashboardService.method.getDashboards;

/**
 * @generated from rpc api.DashboardService.GetDashboard
 */
export const getDashboard = DashboardService.method.getDashboard;

/**
 * @generated from rpc api.DashboardService.GetModelRunDashboard
 */
export const getModelRunDashboard = DashboardService.method.getModelRunDashboard;
