// @generated by protoc-gen-es v2.2.5 with parameter "target=ts"
// @generated from file api/dashboard.proto (package dashboard, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file api/dashboard.proto.
 */
export const file_api_dashboard: GenFile = /*@__PURE__*/
  fileDesc("ChNhcGkvZGFzaGJvYXJkLnByb3RvEglkYXNoYm9hcmQiSwoWQ3JlYXRlRGFzaGJvYXJkUmVxdWVzdBIPCgdtb2RlbElkGAEgASgJEgwKBG5hbWUYAiABKAkSEgoKZGVmaW5pdGlvbhgDIAEoCSIlChdDcmVhdGVEYXNoYm9hcmRSZXNwb25zZRIKCgJpZBgBIAEoCSJ1ChRHZXREYXNoYm9hcmRzUmVxdWVzdBITCgt3b3Jrc3BhY2VJZBgBIAEoCRIUCgdtb2RlbElkGAIgASgJSACIAQESFwoKbW9kZWxSdW5JZBgDIAEoCUgBiAEBQgoKCF9tb2RlbElkQg0KC19tb2RlbFJ1bklkIkEKFUdldERhc2hib2FyZHNSZXNwb25zZRIoCgpkYXNoYm9hcmRzGAEgAygLMhQuZGFzaGJvYXJkLkRhc2hib2FyZCIhChNHZXREYXNoYm9hcmRSZXF1ZXN0EgoKAmlkGAEgASgJIj8KFEdldERhc2hib2FyZFJlc3BvbnNlEicKCWRhc2hib2FyZBgBIAEoCzIULmRhc2hib2FyZC5EYXNoYm9hcmQiRgobR2V0TW9kZWxSdW5EYXNoYm9hcmRSZXF1ZXN0EhIKCm1vZGVsUnVuSWQYASABKAkSEwoLZGFzaGJvYXJkSWQYAiABKAkiNwocR2V0TW9kZWxSdW5EYXNoYm9hcmRSZXNwb25zZRIXCg9kYXNoYm9hcmRTYXNVcmwYASABKAkiNgoJRGFzaGJvYXJkEgoKAmlkGAEgASgJEg8KB21vZGVsSWQYAiABKAkSDAoEbmFtZRgDIAEoCTL6AgoQRGFzaGJvYXJkU2VydmljZRJYCg9DcmVhdGVEYXNoYm9hcmQSIS5kYXNoYm9hcmQuQ3JlYXRlRGFzaGJvYXJkUmVxdWVzdBoiLmRhc2hib2FyZC5DcmVhdGVEYXNoYm9hcmRSZXNwb25zZRJSCg1HZXREYXNoYm9hcmRzEh8uZGFzaGJvYXJkLkdldERhc2hib2FyZHNSZXF1ZXN0GiAuZGFzaGJvYXJkLkdldERhc2hib2FyZHNSZXNwb25zZRJPCgxHZXREYXNoYm9hcmQSHi5kYXNoYm9hcmQuR2V0RGFzaGJvYXJkUmVxdWVzdBofLmRhc2hib2FyZC5HZXREYXNoYm9hcmRSZXNwb25zZRJnChRHZXRNb2RlbFJ1bkRhc2hib2FyZBImLmRhc2hib2FyZC5HZXRNb2RlbFJ1bkRhc2hib2FyZFJlcXVlc3QaJy5kYXNoYm9hcmQuR2V0TW9kZWxSdW5EYXNoYm9hcmRSZXNwb25zZUIpWidnaXRodWIuY29tL01vcmhhZkFsc2hpYmx5L2l1bnZpL2dlbi9hcGliBnByb3RvMw");

/**
 * @generated from message dashboard.CreateDashboardRequest
 */
export type CreateDashboardRequest = Message<"dashboard.CreateDashboardRequest"> & {
  /**
   * @generated from field: string modelId = 1;
   */
  modelId: string;

  /**
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * @generated from field: string definition = 3;
   */
  definition: string;
};

/**
 * Describes the message dashboard.CreateDashboardRequest.
 * Use `create(CreateDashboardRequestSchema)` to create a new message.
 */
export const CreateDashboardRequestSchema: GenMessage<CreateDashboardRequest> = /*@__PURE__*/
  messageDesc(file_api_dashboard, 0);

/**
 * @generated from message dashboard.CreateDashboardResponse
 */
export type CreateDashboardResponse = Message<"dashboard.CreateDashboardResponse"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;
};

/**
 * Describes the message dashboard.CreateDashboardResponse.
 * Use `create(CreateDashboardResponseSchema)` to create a new message.
 */
export const CreateDashboardResponseSchema: GenMessage<CreateDashboardResponse> = /*@__PURE__*/
  messageDesc(file_api_dashboard, 1);

/**
 * @generated from message dashboard.GetDashboardsRequest
 */
export type GetDashboardsRequest = Message<"dashboard.GetDashboardsRequest"> & {
  /**
   * @generated from field: string workspaceId = 1;
   */
  workspaceId: string;

  /**
   * @generated from field: optional string modelId = 2;
   */
  modelId?: string;

  /**
   * @generated from field: optional string modelRunId = 3;
   */
  modelRunId?: string;
};

/**
 * Describes the message dashboard.GetDashboardsRequest.
 * Use `create(GetDashboardsRequestSchema)` to create a new message.
 */
export const GetDashboardsRequestSchema: GenMessage<GetDashboardsRequest> = /*@__PURE__*/
  messageDesc(file_api_dashboard, 2);

/**
 * @generated from message dashboard.GetDashboardsResponse
 */
export type GetDashboardsResponse = Message<"dashboard.GetDashboardsResponse"> & {
  /**
   * @generated from field: repeated dashboard.Dashboard dashboards = 1;
   */
  dashboards: Dashboard[];
};

/**
 * Describes the message dashboard.GetDashboardsResponse.
 * Use `create(GetDashboardsResponseSchema)` to create a new message.
 */
export const GetDashboardsResponseSchema: GenMessage<GetDashboardsResponse> = /*@__PURE__*/
  messageDesc(file_api_dashboard, 3);

/**
 * @generated from message dashboard.GetDashboardRequest
 */
export type GetDashboardRequest = Message<"dashboard.GetDashboardRequest"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;
};

/**
 * Describes the message dashboard.GetDashboardRequest.
 * Use `create(GetDashboardRequestSchema)` to create a new message.
 */
export const GetDashboardRequestSchema: GenMessage<GetDashboardRequest> = /*@__PURE__*/
  messageDesc(file_api_dashboard, 4);

/**
 * @generated from message dashboard.GetDashboardResponse
 */
export type GetDashboardResponse = Message<"dashboard.GetDashboardResponse"> & {
  /**
   * @generated from field: dashboard.Dashboard dashboard = 1;
   */
  dashboard?: Dashboard;
};

/**
 * Describes the message dashboard.GetDashboardResponse.
 * Use `create(GetDashboardResponseSchema)` to create a new message.
 */
export const GetDashboardResponseSchema: GenMessage<GetDashboardResponse> = /*@__PURE__*/
  messageDesc(file_api_dashboard, 5);

/**
 * @generated from message dashboard.GetModelRunDashboardRequest
 */
export type GetModelRunDashboardRequest = Message<"dashboard.GetModelRunDashboardRequest"> & {
  /**
   * @generated from field: string modelRunId = 1;
   */
  modelRunId: string;

  /**
   * @generated from field: string dashboardId = 2;
   */
  dashboardId: string;
};

/**
 * Describes the message dashboard.GetModelRunDashboardRequest.
 * Use `create(GetModelRunDashboardRequestSchema)` to create a new message.
 */
export const GetModelRunDashboardRequestSchema: GenMessage<GetModelRunDashboardRequest> = /*@__PURE__*/
  messageDesc(file_api_dashboard, 6);

/**
 * @generated from message dashboard.GetModelRunDashboardResponse
 */
export type GetModelRunDashboardResponse = Message<"dashboard.GetModelRunDashboardResponse"> & {
  /**
   * @generated from field: string dashboardSasUrl = 1;
   */
  dashboardSasUrl: string;
};

/**
 * Describes the message dashboard.GetModelRunDashboardResponse.
 * Use `create(GetModelRunDashboardResponseSchema)` to create a new message.
 */
export const GetModelRunDashboardResponseSchema: GenMessage<GetModelRunDashboardResponse> = /*@__PURE__*/
  messageDesc(file_api_dashboard, 7);

/**
 * @generated from message dashboard.Dashboard
 */
export type Dashboard = Message<"dashboard.Dashboard"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string modelId = 2;
   */
  modelId: string;

  /**
   * @generated from field: string name = 3;
   */
  name: string;
};

/**
 * Describes the message dashboard.Dashboard.
 * Use `create(DashboardSchema)` to create a new message.
 */
export const DashboardSchema: GenMessage<Dashboard> = /*@__PURE__*/
  messageDesc(file_api_dashboard, 8);

/**
 * @generated from service dashboard.DashboardService
 */
export const DashboardService: GenService<{
  /**
   * @generated from rpc dashboard.DashboardService.CreateDashboard
   */
  createDashboard: {
    methodKind: "unary";
    input: typeof CreateDashboardRequestSchema;
    output: typeof CreateDashboardResponseSchema;
  },
  /**
   * @generated from rpc dashboard.DashboardService.GetDashboards
   */
  getDashboards: {
    methodKind: "unary";
    input: typeof GetDashboardsRequestSchema;
    output: typeof GetDashboardsResponseSchema;
  },
  /**
   * @generated from rpc dashboard.DashboardService.GetDashboard
   */
  getDashboard: {
    methodKind: "unary";
    input: typeof GetDashboardRequestSchema;
    output: typeof GetDashboardResponseSchema;
  },
  /**
   * @generated from rpc dashboard.DashboardService.GetModelRunDashboard
   */
  getModelRunDashboard: {
    methodKind: "unary";
    input: typeof GetModelRunDashboardRequestSchema;
    output: typeof GetModelRunDashboardResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_api_dashboard, 0);

