// @generated by protoc-gen-es v2.2.5 with parameter "target=ts"
// @generated from file api/dashboard.proto (package api, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";
import type { Dashboard } from "./types_pb";
import { file_api_types } from "./types_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file api/dashboard.proto.
 */
export const file_api_dashboard: GenFile = /*@__PURE__*/
  fileDesc("ChNhcGkvZGFzaGJvYXJkLnByb3RvEgNhcGkiSwoWQ3JlYXRlRGFzaGJvYXJkUmVxdWVzdBIPCgdtb2RlbElkGAEgASgJEgwKBG5hbWUYAiABKAkSEgoKZGVmaW5pdGlvbhgDIAEoCSIlChdDcmVhdGVEYXNoYm9hcmRSZXNwb25zZRIKCgJpZBgBIAEoCSJ1ChRHZXREYXNoYm9hcmRzUmVxdWVzdBITCgt3b3Jrc3BhY2VJZBgBIAEoCRIUCgdtb2RlbElkGAIgASgJSACIAQESFwoKbW9kZWxSdW5JZBgDIAEoCUgBiAEBQgoKCF9tb2RlbElkQg0KC19tb2RlbFJ1bklkIjsKFUdldERhc2hib2FyZHNSZXNwb25zZRIiCgpkYXNoYm9hcmRzGAEgAygLMg4uYXBpLkRhc2hib2FyZCIhChNHZXREYXNoYm9hcmRSZXF1ZXN0EgoKAmlkGAEgASgJIjkKFEdldERhc2hib2FyZFJlc3BvbnNlEiEKCWRhc2hib2FyZBgBIAEoCzIOLmFwaS5EYXNoYm9hcmQiRgobR2V0TW9kZWxSdW5EYXNoYm9hcmRSZXF1ZXN0EhIKCm1vZGVsUnVuSWQYASABKAkSEwoLZGFzaGJvYXJkSWQYAiABKAkiNwocR2V0TW9kZWxSdW5EYXNoYm9hcmRSZXNwb25zZRIXCg9kYXNoYm9hcmRTYXNVcmwYASABKAkyygIKEERhc2hib2FyZFNlcnZpY2USTAoPQ3JlYXRlRGFzaGJvYXJkEhsuYXBpLkNyZWF0ZURhc2hib2FyZFJlcXVlc3QaHC5hcGkuQ3JlYXRlRGFzaGJvYXJkUmVzcG9uc2USRgoNR2V0RGFzaGJvYXJkcxIZLmFwaS5HZXREYXNoYm9hcmRzUmVxdWVzdBoaLmFwaS5HZXREYXNoYm9hcmRzUmVzcG9uc2USQwoMR2V0RGFzaGJvYXJkEhguYXBpLkdldERhc2hib2FyZFJlcXVlc3QaGS5hcGkuR2V0RGFzaGJvYXJkUmVzcG9uc2USWwoUR2V0TW9kZWxSdW5EYXNoYm9hcmQSIC5hcGkuR2V0TW9kZWxSdW5EYXNoYm9hcmRSZXF1ZXN0GiEuYXBpLkdldE1vZGVsUnVuRGFzaGJvYXJkUmVzcG9uc2VCKVonZ2l0aHViLmNvbS9Nb3JoYWZBbHNoaWJseS9pdW52aS9nZW4vYXBpYgZwcm90bzM", [file_api_types]);

/**
 * @generated from message api.CreateDashboardRequest
 */
export type CreateDashboardRequest = Message<"api.CreateDashboardRequest"> & {
  /**
   * @generated from field: string modelId = 1;
   */
  modelId: string;

  /**
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * @generated from field: string definition = 3;
   */
  definition: string;
};

/**
 * Describes the message api.CreateDashboardRequest.
 * Use `create(CreateDashboardRequestSchema)` to create a new message.
 */
export const CreateDashboardRequestSchema: GenMessage<CreateDashboardRequest> = /*@__PURE__*/
  messageDesc(file_api_dashboard, 0);

/**
 * @generated from message api.CreateDashboardResponse
 */
export type CreateDashboardResponse = Message<"api.CreateDashboardResponse"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;
};

/**
 * Describes the message api.CreateDashboardResponse.
 * Use `create(CreateDashboardResponseSchema)` to create a new message.
 */
export const CreateDashboardResponseSchema: GenMessage<CreateDashboardResponse> = /*@__PURE__*/
  messageDesc(file_api_dashboard, 1);

/**
 * @generated from message api.GetDashboardsRequest
 */
export type GetDashboardsRequest = Message<"api.GetDashboardsRequest"> & {
  /**
   * @generated from field: string workspaceId = 1;
   */
  workspaceId: string;

  /**
   * @generated from field: optional string modelId = 2;
   */
  modelId?: string;

  /**
   * @generated from field: optional string modelRunId = 3;
   */
  modelRunId?: string;
};

/**
 * Describes the message api.GetDashboardsRequest.
 * Use `create(GetDashboardsRequestSchema)` to create a new message.
 */
export const GetDashboardsRequestSchema: GenMessage<GetDashboardsRequest> = /*@__PURE__*/
  messageDesc(file_api_dashboard, 2);

/**
 * @generated from message api.GetDashboardsResponse
 */
export type GetDashboardsResponse = Message<"api.GetDashboardsResponse"> & {
  /**
   * @generated from field: repeated api.Dashboard dashboards = 1;
   */
  dashboards: Dashboard[];
};

/**
 * Describes the message api.GetDashboardsResponse.
 * Use `create(GetDashboardsResponseSchema)` to create a new message.
 */
export const GetDashboardsResponseSchema: GenMessage<GetDashboardsResponse> = /*@__PURE__*/
  messageDesc(file_api_dashboard, 3);

/**
 * @generated from message api.GetDashboardRequest
 */
export type GetDashboardRequest = Message<"api.GetDashboardRequest"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;
};

/**
 * Describes the message api.GetDashboardRequest.
 * Use `create(GetDashboardRequestSchema)` to create a new message.
 */
export const GetDashboardRequestSchema: GenMessage<GetDashboardRequest> = /*@__PURE__*/
  messageDesc(file_api_dashboard, 4);

/**
 * @generated from message api.GetDashboardResponse
 */
export type GetDashboardResponse = Message<"api.GetDashboardResponse"> & {
  /**
   * @generated from field: api.Dashboard dashboard = 1;
   */
  dashboard?: Dashboard;
};

/**
 * Describes the message api.GetDashboardResponse.
 * Use `create(GetDashboardResponseSchema)` to create a new message.
 */
export const GetDashboardResponseSchema: GenMessage<GetDashboardResponse> = /*@__PURE__*/
  messageDesc(file_api_dashboard, 5);

/**
 * @generated from message api.GetModelRunDashboardRequest
 */
export type GetModelRunDashboardRequest = Message<"api.GetModelRunDashboardRequest"> & {
  /**
   * @generated from field: string modelRunId = 1;
   */
  modelRunId: string;

  /**
   * @generated from field: string dashboardId = 2;
   */
  dashboardId: string;
};

/**
 * Describes the message api.GetModelRunDashboardRequest.
 * Use `create(GetModelRunDashboardRequestSchema)` to create a new message.
 */
export const GetModelRunDashboardRequestSchema: GenMessage<GetModelRunDashboardRequest> = /*@__PURE__*/
  messageDesc(file_api_dashboard, 6);

/**
 * @generated from message api.GetModelRunDashboardResponse
 */
export type GetModelRunDashboardResponse = Message<"api.GetModelRunDashboardResponse"> & {
  /**
   * @generated from field: string dashboardSasUrl = 1;
   */
  dashboardSasUrl: string;
};

/**
 * Describes the message api.GetModelRunDashboardResponse.
 * Use `create(GetModelRunDashboardResponseSchema)` to create a new message.
 */
export const GetModelRunDashboardResponseSchema: GenMessage<GetModelRunDashboardResponse> = /*@__PURE__*/
  messageDesc(file_api_dashboard, 7);

/**
 * @generated from service api.DashboardService
 */
export const DashboardService: GenService<{
  /**
   * @generated from rpc api.DashboardService.CreateDashboard
   */
  createDashboard: {
    methodKind: "unary";
    input: typeof CreateDashboardRequestSchema;
    output: typeof CreateDashboardResponseSchema;
  },
  /**
   * @generated from rpc api.DashboardService.GetDashboards
   */
  getDashboards: {
    methodKind: "unary";
    input: typeof GetDashboardsRequestSchema;
    output: typeof GetDashboardsResponseSchema;
  },
  /**
   * @generated from rpc api.DashboardService.GetDashboard
   */
  getDashboard: {
    methodKind: "unary";
    input: typeof GetDashboardRequestSchema;
    output: typeof GetDashboardResponseSchema;
  },
  /**
   * @generated from rpc api.DashboardService.GetModelRunDashboard
   */
  getModelRunDashboard: {
    methodKind: "unary";
    input: typeof GetModelRunDashboardRequestSchema;
    output: typeof GetModelRunDashboardResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_api_dashboard, 0);

