// @generated by protoc-gen-connect-query v2.0.1 with parameter "target=ts"
// @generated from file api/file.proto (package api, syntax proto3)
/* eslint-disable */

import { FileService } from "./file_pb";

/**
 * @generated from rpc api.FileService.CreateSpecification
 */
export const createSpecification = FileService.method.createSpecification;

/**
 * @generated from rpc api.FileService.GetSpecifications
 */
export const getSpecifications = FileService.method.getSpecifications;

/**
 * @generated from rpc api.FileService.GetSpecification
 */
export const getSpecification = FileService.method.getSpecification;

/**
 * @generated from rpc api.FileService.CreateLandingZoneSharedAccessSignature
 */
export const createLandingZoneSharedAccessSignature = FileService.method.createLandingZoneSharedAccessSignature;

/**
 * @generated from rpc api.FileService.GetLandingZoneFiles
 */
export const getLandingZoneFiles = FileService.method.getLandingZoneFiles;

/**
 * @generated from rpc api.FileService.CreateFileGroup
 */
export const createFileGroup = FileService.method.createFileGroup;

/**
 * @generated from rpc api.FileService.GetFileGroups
 */
export const getFileGroups = FileService.method.getFileGroups;
