// @generated by protoc-gen-connect-query v2.0.1 with parameter "target=ts"
// @generated from file api/model.proto (package api, syntax proto3)
/* eslint-disable */

import { ModelService } from "./model_pb";

/**
 * @generated from rpc api.ModelService.GetRegistryTokenPasswords
 */
export const getRegistryTokenPasswords = ModelService.method.getRegistryTokenPasswords;

/**
 * @generated from rpc api.ModelService.CreateRegistryTokenPassword
 */
export const createRegistryTokenPassword = ModelService.method.createRegistryTokenPassword;

/**
 * @generated from rpc api.ModelService.GetImages
 */
export const getImages = ModelService.method.getImages;

/**
 * @generated from rpc api.ModelService.CreateModel
 */
export const createModel = ModelService.method.createModel;

/**
 * @generated from rpc api.ModelService.GetModels
 */
export const getModels = ModelService.method.getModels;

/**
 * @generated from rpc api.ModelService.GetModel
 */
export const getModel = ModelService.method.getModel;

/**
 * @generated from rpc api.ModelService.CreateModelRun
 */
export const createModelRun = ModelService.method.createModelRun;

/**
 * @generated from rpc api.ModelService.GetModelRuns
 */
export const getModelRuns = ModelService.method.getModelRuns;
