// @generated by protoc-gen-connect-query v2.0.1 with parameter "target=ts"
// @generated from file api/tenantManagement.proto (package api, syntax proto3)
/* eslint-disable */

import { TenantManagementService } from "./tenantManagement_pb";

/**
 * @generated from rpc api.TenantManagementService.CreateWorkspace
 */
export const createWorkspace = TenantManagementService.method.createWorkspace;

/**
 * @generated from rpc api.TenantManagementService.GetWorkspaces
 */
export const getWorkspaces = TenantManagementService.method.getWorkspaces;

/**
 * @generated from rpc api.TenantManagementService.EditWorkspace
 */
export const editWorkspace = TenantManagementService.method.editWorkspace;

/**
 * @generated from rpc api.TenantManagementService.GetUsers
 */
export const getUsers = TenantManagementService.method.getUsers;

/**
 * @generated from rpc api.TenantManagementService.GetUserWorkspaceAssignment
 */
export const getUserWorkspaceAssignment = TenantManagementService.method.getUserWorkspaceAssignment;

/**
 * @generated from rpc api.TenantManagementService.AssignUserToWorkspace
 */
export const assignUserToWorkspace = TenantManagementService.method.assignUserToWorkspace;

/**
 * @generated from rpc api.TenantManagementService.GetRegistryTokenPasswords
 */
export const getRegistryTokenPasswords = TenantManagementService.method.getRegistryTokenPasswords;

/**
 * @generated from rpc api.TenantManagementService.CreateRegistryTokenPassword
 */
export const createRegistryTokenPassword = TenantManagementService.method.createRegistryTokenPassword;

/**
 * @generated from rpc api.TenantManagementService.GetImages
 */
export const getImages = TenantManagementService.method.getImages;

/**
 * @generated from rpc api.TenantManagementService.CreateSpecification
 */
export const createSpecification = TenantManagementService.method.createSpecification;

/**
 * @generated from rpc api.TenantManagementService.GetSpecifications
 */
export const getSpecifications = TenantManagementService.method.getSpecifications;

/**
 * @generated from rpc api.TenantManagementService.GetSpecification
 */
export const getSpecification = TenantManagementService.method.getSpecification;

/**
 * @generated from rpc api.TenantManagementService.CreateLandingZoneSharedAccessSignature
 */
export const createLandingZoneSharedAccessSignature = TenantManagementService.method.createLandingZoneSharedAccessSignature;

/**
 * @generated from rpc api.TenantManagementService.GetLandingZoneFiles
 */
export const getLandingZoneFiles = TenantManagementService.method.getLandingZoneFiles;

/**
 * @generated from rpc api.TenantManagementService.CreateFileGroup
 */
export const createFileGroup = TenantManagementService.method.createFileGroup;
