// @generated by protoc-gen-es v2.2.5 with parameter "target=ts"
// @generated from file api/tenant.proto (package tenant, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv1";
import { enumDesc, fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file api/tenant.proto.
 */
export const file_api_tenant: GenFile = /*@__PURE__*/
  fileDesc("ChBhcGkvdGVuYW50LnByb3RvEgZ0ZW5hbnQiJgoWQ3JlYXRlV29ya3NwYWNlUmVxdWVzdBIMCgRuYW1lGAEgASgJIiUKF0NyZWF0ZVdvcmtzcGFjZVJlc3BvbnNlEgoKAmlkGAEgASgJIhYKFEdldFdvcmtzcGFjZXNSZXF1ZXN0Ij4KFUdldFdvcmtzcGFjZXNSZXNwb25zZRIlCgp3b3Jrc3BhY2VzGAEgAygLMhEudGVuYW50LldvcmtzcGFjZSIwChRFZGl0V29ya3NwYWNlUmVxdWVzdBIKCgJpZBgBIAEoCRIMCgRuYW1lGAIgASgJIhcKFUVkaXRXb3Jrc3BhY2VSZXNwb25zZSIRCg9HZXRVc2Vyc1JlcXVlc3QiLwoQR2V0VXNlcnNSZXNwb25zZRIbCgV1c2VycxgBIAMoCzIMLnRlbmFudC5Vc2VyIk4KIUdldFVzZXJXb3Jrc3BhY2VBc3NpZ25tZW50UmVxdWVzdBIUCgx1c2VyT2JqZWN0SWQYASABKAkSEwoLd29ya3NwYWNlSWQYAiABKAkiSQoiR2V0VXNlcldvcmtzcGFjZUFzc2lnbm1lbnRSZXNwb25zZRIjCgRyb2xlGAEgASgOMhUudGVuYW50LldvcmtzcGFjZVJvbGUibgocQXNzaWduVXNlclRvV29ya3NwYWNlUmVxdWVzdBIUCgx1c2VyT2JqZWN0SWQYASABKAkSEwoLd29ya3NwYWNlSWQYAiABKAkSIwoEcm9sZRgDIAEoDjIVLnRlbmFudC5Xb3Jrc3BhY2VSb2xlIh8KHUFzc2lnblVzZXJUb1dvcmtzcGFjZVJlc3BvbnNlIiUKCVdvcmtzcGFjZRIKCgJpZBgBIAEoCRIMCgRuYW1lGAIgASgJIjkKBFVzZXISCgoCaWQYASABKAkSEAoIdXNlcm5hbWUYAiABKAkSEwoLZGlzcGxheU5hbWUYAyABKAkqRAoNV29ya3NwYWNlUm9sZRIOCgpVTkFTU0lHTkVEEAASCgoGVklFV0VSEAESCAoEVVNFUhACEg0KCURFVkVMT1BFUhADMpkECg1UZW5hbnRTZXJ2aWNlElIKD0NyZWF0ZVdvcmtzcGFjZRIeLnRlbmFudC5DcmVhdGVXb3Jrc3BhY2VSZXF1ZXN0Gh8udGVuYW50LkNyZWF0ZVdvcmtzcGFjZVJlc3BvbnNlEkwKDUdldFdvcmtzcGFjZXMSHC50ZW5hbnQuR2V0V29ya3NwYWNlc1JlcXVlc3QaHS50ZW5hbnQuR2V0V29ya3NwYWNlc1Jlc3BvbnNlEkwKDUVkaXRXb3Jrc3BhY2USHC50ZW5hbnQuRWRpdFdvcmtzcGFjZVJlcXVlc3QaHS50ZW5hbnQuRWRpdFdvcmtzcGFjZVJlc3BvbnNlEj0KCEdldFVzZXJzEhcudGVuYW50LkdldFVzZXJzUmVxdWVzdBoYLnRlbmFudC5HZXRVc2Vyc1Jlc3BvbnNlEnMKGkdldFVzZXJXb3Jrc3BhY2VBc3NpZ25tZW50EikudGVuYW50LkdldFVzZXJXb3Jrc3BhY2VBc3NpZ25tZW50UmVxdWVzdBoqLnRlbmFudC5HZXRVc2VyV29ya3NwYWNlQXNzaWdubWVudFJlc3BvbnNlEmQKFUFzc2lnblVzZXJUb1dvcmtzcGFjZRIkLnRlbmFudC5Bc3NpZ25Vc2VyVG9Xb3Jrc3BhY2VSZXF1ZXN0GiUudGVuYW50LkFzc2lnblVzZXJUb1dvcmtzcGFjZVJlc3BvbnNlQilaJ2dpdGh1Yi5jb20vTW9yaGFmQWxzaGlibHkvaXVudmkvZ2VuL2FwaWIGcHJvdG8z");

/**
 * @generated from message tenant.CreateWorkspaceRequest
 */
export type CreateWorkspaceRequest = Message<"tenant.CreateWorkspaceRequest"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;
};

/**
 * Describes the message tenant.CreateWorkspaceRequest.
 * Use `create(CreateWorkspaceRequestSchema)` to create a new message.
 */
export const CreateWorkspaceRequestSchema: GenMessage<CreateWorkspaceRequest> = /*@__PURE__*/
  messageDesc(file_api_tenant, 0);

/**
 * @generated from message tenant.CreateWorkspaceResponse
 */
export type CreateWorkspaceResponse = Message<"tenant.CreateWorkspaceResponse"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;
};

/**
 * Describes the message tenant.CreateWorkspaceResponse.
 * Use `create(CreateWorkspaceResponseSchema)` to create a new message.
 */
export const CreateWorkspaceResponseSchema: GenMessage<CreateWorkspaceResponse> = /*@__PURE__*/
  messageDesc(file_api_tenant, 1);

/**
 * @generated from message tenant.GetWorkspacesRequest
 */
export type GetWorkspacesRequest = Message<"tenant.GetWorkspacesRequest"> & {
};

/**
 * Describes the message tenant.GetWorkspacesRequest.
 * Use `create(GetWorkspacesRequestSchema)` to create a new message.
 */
export const GetWorkspacesRequestSchema: GenMessage<GetWorkspacesRequest> = /*@__PURE__*/
  messageDesc(file_api_tenant, 2);

/**
 * @generated from message tenant.GetWorkspacesResponse
 */
export type GetWorkspacesResponse = Message<"tenant.GetWorkspacesResponse"> & {
  /**
   * @generated from field: repeated tenant.Workspace workspaces = 1;
   */
  workspaces: Workspace[];
};

/**
 * Describes the message tenant.GetWorkspacesResponse.
 * Use `create(GetWorkspacesResponseSchema)` to create a new message.
 */
export const GetWorkspacesResponseSchema: GenMessage<GetWorkspacesResponse> = /*@__PURE__*/
  messageDesc(file_api_tenant, 3);

/**
 * @generated from message tenant.EditWorkspaceRequest
 */
export type EditWorkspaceRequest = Message<"tenant.EditWorkspaceRequest"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string name = 2;
   */
  name: string;
};

/**
 * Describes the message tenant.EditWorkspaceRequest.
 * Use `create(EditWorkspaceRequestSchema)` to create a new message.
 */
export const EditWorkspaceRequestSchema: GenMessage<EditWorkspaceRequest> = /*@__PURE__*/
  messageDesc(file_api_tenant, 4);

/**
 * @generated from message tenant.EditWorkspaceResponse
 */
export type EditWorkspaceResponse = Message<"tenant.EditWorkspaceResponse"> & {
};

/**
 * Describes the message tenant.EditWorkspaceResponse.
 * Use `create(EditWorkspaceResponseSchema)` to create a new message.
 */
export const EditWorkspaceResponseSchema: GenMessage<EditWorkspaceResponse> = /*@__PURE__*/
  messageDesc(file_api_tenant, 5);

/**
 * @generated from message tenant.GetUsersRequest
 */
export type GetUsersRequest = Message<"tenant.GetUsersRequest"> & {
};

/**
 * Describes the message tenant.GetUsersRequest.
 * Use `create(GetUsersRequestSchema)` to create a new message.
 */
export const GetUsersRequestSchema: GenMessage<GetUsersRequest> = /*@__PURE__*/
  messageDesc(file_api_tenant, 6);

/**
 * @generated from message tenant.GetUsersResponse
 */
export type GetUsersResponse = Message<"tenant.GetUsersResponse"> & {
  /**
   * @generated from field: repeated tenant.User users = 1;
   */
  users: User[];
};

/**
 * Describes the message tenant.GetUsersResponse.
 * Use `create(GetUsersResponseSchema)` to create a new message.
 */
export const GetUsersResponseSchema: GenMessage<GetUsersResponse> = /*@__PURE__*/
  messageDesc(file_api_tenant, 7);

/**
 * @generated from message tenant.GetUserWorkspaceAssignmentRequest
 */
export type GetUserWorkspaceAssignmentRequest = Message<"tenant.GetUserWorkspaceAssignmentRequest"> & {
  /**
   * @generated from field: string userObjectId = 1;
   */
  userObjectId: string;

  /**
   * @generated from field: string workspaceId = 2;
   */
  workspaceId: string;
};

/**
 * Describes the message tenant.GetUserWorkspaceAssignmentRequest.
 * Use `create(GetUserWorkspaceAssignmentRequestSchema)` to create a new message.
 */
export const GetUserWorkspaceAssignmentRequestSchema: GenMessage<GetUserWorkspaceAssignmentRequest> = /*@__PURE__*/
  messageDesc(file_api_tenant, 8);

/**
 * @generated from message tenant.GetUserWorkspaceAssignmentResponse
 */
export type GetUserWorkspaceAssignmentResponse = Message<"tenant.GetUserWorkspaceAssignmentResponse"> & {
  /**
   * @generated from field: tenant.WorkspaceRole role = 1;
   */
  role: WorkspaceRole;
};

/**
 * Describes the message tenant.GetUserWorkspaceAssignmentResponse.
 * Use `create(GetUserWorkspaceAssignmentResponseSchema)` to create a new message.
 */
export const GetUserWorkspaceAssignmentResponseSchema: GenMessage<GetUserWorkspaceAssignmentResponse> = /*@__PURE__*/
  messageDesc(file_api_tenant, 9);

/**
 * @generated from message tenant.AssignUserToWorkspaceRequest
 */
export type AssignUserToWorkspaceRequest = Message<"tenant.AssignUserToWorkspaceRequest"> & {
  /**
   * @generated from field: string userObjectId = 1;
   */
  userObjectId: string;

  /**
   * @generated from field: string workspaceId = 2;
   */
  workspaceId: string;

  /**
   * @generated from field: tenant.WorkspaceRole role = 3;
   */
  role: WorkspaceRole;
};

/**
 * Describes the message tenant.AssignUserToWorkspaceRequest.
 * Use `create(AssignUserToWorkspaceRequestSchema)` to create a new message.
 */
export const AssignUserToWorkspaceRequestSchema: GenMessage<AssignUserToWorkspaceRequest> = /*@__PURE__*/
  messageDesc(file_api_tenant, 10);

/**
 * @generated from message tenant.AssignUserToWorkspaceResponse
 */
export type AssignUserToWorkspaceResponse = Message<"tenant.AssignUserToWorkspaceResponse"> & {
};

/**
 * Describes the message tenant.AssignUserToWorkspaceResponse.
 * Use `create(AssignUserToWorkspaceResponseSchema)` to create a new message.
 */
export const AssignUserToWorkspaceResponseSchema: GenMessage<AssignUserToWorkspaceResponse> = /*@__PURE__*/
  messageDesc(file_api_tenant, 11);

/**
 * @generated from message tenant.Workspace
 */
export type Workspace = Message<"tenant.Workspace"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string name = 2;
   */
  name: string;
};

/**
 * Describes the message tenant.Workspace.
 * Use `create(WorkspaceSchema)` to create a new message.
 */
export const WorkspaceSchema: GenMessage<Workspace> = /*@__PURE__*/
  messageDesc(file_api_tenant, 12);

/**
 * @generated from message tenant.User
 */
export type User = Message<"tenant.User"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string username = 2;
   */
  username: string;

  /**
   * @generated from field: string displayName = 3;
   */
  displayName: string;
};

/**
 * Describes the message tenant.User.
 * Use `create(UserSchema)` to create a new message.
 */
export const UserSchema: GenMessage<User> = /*@__PURE__*/
  messageDesc(file_api_tenant, 13);

/**
 * @generated from enum tenant.WorkspaceRole
 */
export enum WorkspaceRole {
  /**
   * @generated from enum value: UNASSIGNED = 0;
   */
  UNASSIGNED = 0,

  /**
   * @generated from enum value: VIEWER = 1;
   */
  VIEWER = 1,

  /**
   * @generated from enum value: USER = 2;
   */
  USER = 2,

  /**
   * @generated from enum value: DEVELOPER = 3;
   */
  DEVELOPER = 3,
}

/**
 * Describes the enum tenant.WorkspaceRole.
 */
export const WorkspaceRoleSchema: GenEnum<WorkspaceRole> = /*@__PURE__*/
  enumDesc(file_api_tenant, 0);

/**
 * @generated from service tenant.TenantService
 */
export const TenantService: GenService<{
  /**
   * @generated from rpc tenant.TenantService.CreateWorkspace
   */
  createWorkspace: {
    methodKind: "unary";
    input: typeof CreateWorkspaceRequestSchema;
    output: typeof CreateWorkspaceResponseSchema;
  },
  /**
   * @generated from rpc tenant.TenantService.GetWorkspaces
   */
  getWorkspaces: {
    methodKind: "unary";
    input: typeof GetWorkspacesRequestSchema;
    output: typeof GetWorkspacesResponseSchema;
  },
  /**
   * @generated from rpc tenant.TenantService.EditWorkspace
   */
  editWorkspace: {
    methodKind: "unary";
    input: typeof EditWorkspaceRequestSchema;
    output: typeof EditWorkspaceResponseSchema;
  },
  /**
   * @generated from rpc tenant.TenantService.GetUsers
   */
  getUsers: {
    methodKind: "unary";
    input: typeof GetUsersRequestSchema;
    output: typeof GetUsersResponseSchema;
  },
  /**
   * @generated from rpc tenant.TenantService.GetUserWorkspaceAssignment
   */
  getUserWorkspaceAssignment: {
    methodKind: "unary";
    input: typeof GetUserWorkspaceAssignmentRequestSchema;
    output: typeof GetUserWorkspaceAssignmentResponseSchema;
  },
  /**
   * @generated from rpc tenant.TenantService.AssignUserToWorkspace
   */
  assignUserToWorkspace: {
    methodKind: "unary";
    input: typeof AssignUserToWorkspaceRequestSchema;
    output: typeof AssignUserToWorkspaceResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_api_tenant, 0);

