// @generated by protoc-gen-es v2.2.5 with parameter "target=ts"
// @generated from file api/tenant.proto (package api, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";
import type { User, Workspace, WorkspaceRole } from "./types_pb";
import { file_api_types } from "./types_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file api/tenant.proto.
 */
export const file_api_tenant: GenFile = /*@__PURE__*/
  fileDesc("ChBhcGkvdGVuYW50LnByb3RvEgNhcGkiJgoWQ3JlYXRlV29ya3NwYWNlUmVxdWVzdBIMCgRuYW1lGAEgASgJIiUKF0NyZWF0ZVdvcmtzcGFjZVJlc3BvbnNlEgoKAmlkGAEgASgJIhYKFEdldFdvcmtzcGFjZXNSZXF1ZXN0IjsKFUdldFdvcmtzcGFjZXNSZXNwb25zZRIiCgp3b3Jrc3BhY2VzGAEgAygLMg4uYXBpLldvcmtzcGFjZSIwChRFZGl0V29ya3NwYWNlUmVxdWVzdBIKCgJpZBgBIAEoCRIMCgRuYW1lGAIgASgJIhcKFUVkaXRXb3Jrc3BhY2VSZXNwb25zZSIRCg9HZXRVc2Vyc1JlcXVlc3QiLAoQR2V0VXNlcnNSZXNwb25zZRIYCgV1c2VycxgBIAMoCzIJLmFwaS5Vc2VyIk4KIUdldFVzZXJXb3Jrc3BhY2VBc3NpZ25tZW50UmVxdWVzdBIUCgx1c2VyT2JqZWN0SWQYASABKAkSEwoLd29ya3NwYWNlSWQYAiABKAkiRgoiR2V0VXNlcldvcmtzcGFjZUFzc2lnbm1lbnRSZXNwb25zZRIgCgRyb2xlGAEgASgOMhIuYXBpLldvcmtzcGFjZVJvbGUiawocQXNzaWduVXNlclRvV29ya3NwYWNlUmVxdWVzdBIUCgx1c2VyT2JqZWN0SWQYASABKAkSEwoLd29ya3NwYWNlSWQYAiABKAkSIAoEcm9sZRgDIAEoDjISLmFwaS5Xb3Jrc3BhY2VSb2xlIh8KHUFzc2lnblVzZXJUb1dvcmtzcGFjZVJlc3BvbnNlMvUDCg1UZW5hbnRTZXJ2aWNlEkwKD0NyZWF0ZVdvcmtzcGFjZRIbLmFwaS5DcmVhdGVXb3Jrc3BhY2VSZXF1ZXN0GhwuYXBpLkNyZWF0ZVdvcmtzcGFjZVJlc3BvbnNlEkYKDUdldFdvcmtzcGFjZXMSGS5hcGkuR2V0V29ya3NwYWNlc1JlcXVlc3QaGi5hcGkuR2V0V29ya3NwYWNlc1Jlc3BvbnNlEkYKDUVkaXRXb3Jrc3BhY2USGS5hcGkuRWRpdFdvcmtzcGFjZVJlcXVlc3QaGi5hcGkuRWRpdFdvcmtzcGFjZVJlc3BvbnNlEjcKCEdldFVzZXJzEhQuYXBpLkdldFVzZXJzUmVxdWVzdBoVLmFwaS5HZXRVc2Vyc1Jlc3BvbnNlEm0KGkdldFVzZXJXb3Jrc3BhY2VBc3NpZ25tZW50EiYuYXBpLkdldFVzZXJXb3Jrc3BhY2VBc3NpZ25tZW50UmVxdWVzdBonLmFwaS5HZXRVc2VyV29ya3NwYWNlQXNzaWdubWVudFJlc3BvbnNlEl4KFUFzc2lnblVzZXJUb1dvcmtzcGFjZRIhLmFwaS5Bc3NpZ25Vc2VyVG9Xb3Jrc3BhY2VSZXF1ZXN0GiIuYXBpLkFzc2lnblVzZXJUb1dvcmtzcGFjZVJlc3BvbnNlQilaJ2dpdGh1Yi5jb20vTW9yaGFmQWxzaGlibHkvaXVudmkvZ2VuL2FwaWIGcHJvdG8z", [file_api_types]);

/**
 * @generated from message api.CreateWorkspaceRequest
 */
export type CreateWorkspaceRequest = Message<"api.CreateWorkspaceRequest"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;
};

/**
 * Describes the message api.CreateWorkspaceRequest.
 * Use `create(CreateWorkspaceRequestSchema)` to create a new message.
 */
export const CreateWorkspaceRequestSchema: GenMessage<CreateWorkspaceRequest> = /*@__PURE__*/
  messageDesc(file_api_tenant, 0);

/**
 * @generated from message api.CreateWorkspaceResponse
 */
export type CreateWorkspaceResponse = Message<"api.CreateWorkspaceResponse"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;
};

/**
 * Describes the message api.CreateWorkspaceResponse.
 * Use `create(CreateWorkspaceResponseSchema)` to create a new message.
 */
export const CreateWorkspaceResponseSchema: GenMessage<CreateWorkspaceResponse> = /*@__PURE__*/
  messageDesc(file_api_tenant, 1);

/**
 * @generated from message api.GetWorkspacesRequest
 */
export type GetWorkspacesRequest = Message<"api.GetWorkspacesRequest"> & {
};

/**
 * Describes the message api.GetWorkspacesRequest.
 * Use `create(GetWorkspacesRequestSchema)` to create a new message.
 */
export const GetWorkspacesRequestSchema: GenMessage<GetWorkspacesRequest> = /*@__PURE__*/
  messageDesc(file_api_tenant, 2);

/**
 * @generated from message api.GetWorkspacesResponse
 */
export type GetWorkspacesResponse = Message<"api.GetWorkspacesResponse"> & {
  /**
   * @generated from field: repeated api.Workspace workspaces = 1;
   */
  workspaces: Workspace[];
};

/**
 * Describes the message api.GetWorkspacesResponse.
 * Use `create(GetWorkspacesResponseSchema)` to create a new message.
 */
export const GetWorkspacesResponseSchema: GenMessage<GetWorkspacesResponse> = /*@__PURE__*/
  messageDesc(file_api_tenant, 3);

/**
 * @generated from message api.EditWorkspaceRequest
 */
export type EditWorkspaceRequest = Message<"api.EditWorkspaceRequest"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string name = 2;
   */
  name: string;
};

/**
 * Describes the message api.EditWorkspaceRequest.
 * Use `create(EditWorkspaceRequestSchema)` to create a new message.
 */
export const EditWorkspaceRequestSchema: GenMessage<EditWorkspaceRequest> = /*@__PURE__*/
  messageDesc(file_api_tenant, 4);

/**
 * @generated from message api.EditWorkspaceResponse
 */
export type EditWorkspaceResponse = Message<"api.EditWorkspaceResponse"> & {
};

/**
 * Describes the message api.EditWorkspaceResponse.
 * Use `create(EditWorkspaceResponseSchema)` to create a new message.
 */
export const EditWorkspaceResponseSchema: GenMessage<EditWorkspaceResponse> = /*@__PURE__*/
  messageDesc(file_api_tenant, 5);

/**
 * @generated from message api.GetUsersRequest
 */
export type GetUsersRequest = Message<"api.GetUsersRequest"> & {
};

/**
 * Describes the message api.GetUsersRequest.
 * Use `create(GetUsersRequestSchema)` to create a new message.
 */
export const GetUsersRequestSchema: GenMessage<GetUsersRequest> = /*@__PURE__*/
  messageDesc(file_api_tenant, 6);

/**
 * @generated from message api.GetUsersResponse
 */
export type GetUsersResponse = Message<"api.GetUsersResponse"> & {
  /**
   * @generated from field: repeated api.User users = 1;
   */
  users: User[];
};

/**
 * Describes the message api.GetUsersResponse.
 * Use `create(GetUsersResponseSchema)` to create a new message.
 */
export const GetUsersResponseSchema: GenMessage<GetUsersResponse> = /*@__PURE__*/
  messageDesc(file_api_tenant, 7);

/**
 * @generated from message api.GetUserWorkspaceAssignmentRequest
 */
export type GetUserWorkspaceAssignmentRequest = Message<"api.GetUserWorkspaceAssignmentRequest"> & {
  /**
   * @generated from field: string userObjectId = 1;
   */
  userObjectId: string;

  /**
   * @generated from field: string workspaceId = 2;
   */
  workspaceId: string;
};

/**
 * Describes the message api.GetUserWorkspaceAssignmentRequest.
 * Use `create(GetUserWorkspaceAssignmentRequestSchema)` to create a new message.
 */
export const GetUserWorkspaceAssignmentRequestSchema: GenMessage<GetUserWorkspaceAssignmentRequest> = /*@__PURE__*/
  messageDesc(file_api_tenant, 8);

/**
 * @generated from message api.GetUserWorkspaceAssignmentResponse
 */
export type GetUserWorkspaceAssignmentResponse = Message<"api.GetUserWorkspaceAssignmentResponse"> & {
  /**
   * @generated from field: api.WorkspaceRole role = 1;
   */
  role: WorkspaceRole;
};

/**
 * Describes the message api.GetUserWorkspaceAssignmentResponse.
 * Use `create(GetUserWorkspaceAssignmentResponseSchema)` to create a new message.
 */
export const GetUserWorkspaceAssignmentResponseSchema: GenMessage<GetUserWorkspaceAssignmentResponse> = /*@__PURE__*/
  messageDesc(file_api_tenant, 9);

/**
 * @generated from message api.AssignUserToWorkspaceRequest
 */
export type AssignUserToWorkspaceRequest = Message<"api.AssignUserToWorkspaceRequest"> & {
  /**
   * @generated from field: string userObjectId = 1;
   */
  userObjectId: string;

  /**
   * @generated from field: string workspaceId = 2;
   */
  workspaceId: string;

  /**
   * @generated from field: api.WorkspaceRole role = 3;
   */
  role: WorkspaceRole;
};

/**
 * Describes the message api.AssignUserToWorkspaceRequest.
 * Use `create(AssignUserToWorkspaceRequestSchema)` to create a new message.
 */
export const AssignUserToWorkspaceRequestSchema: GenMessage<AssignUserToWorkspaceRequest> = /*@__PURE__*/
  messageDesc(file_api_tenant, 10);

/**
 * @generated from message api.AssignUserToWorkspaceResponse
 */
export type AssignUserToWorkspaceResponse = Message<"api.AssignUserToWorkspaceResponse"> & {
};

/**
 * Describes the message api.AssignUserToWorkspaceResponse.
 * Use `create(AssignUserToWorkspaceResponseSchema)` to create a new message.
 */
export const AssignUserToWorkspaceResponseSchema: GenMessage<AssignUserToWorkspaceResponse> = /*@__PURE__*/
  messageDesc(file_api_tenant, 11);

/**
 * @generated from service api.TenantService
 */
export const TenantService: GenService<{
  /**
   * @generated from rpc api.TenantService.CreateWorkspace
   */
  createWorkspace: {
    methodKind: "unary";
    input: typeof CreateWorkspaceRequestSchema;
    output: typeof CreateWorkspaceResponseSchema;
  },
  /**
   * @generated from rpc api.TenantService.GetWorkspaces
   */
  getWorkspaces: {
    methodKind: "unary";
    input: typeof GetWorkspacesRequestSchema;
    output: typeof GetWorkspacesResponseSchema;
  },
  /**
   * @generated from rpc api.TenantService.EditWorkspace
   */
  editWorkspace: {
    methodKind: "unary";
    input: typeof EditWorkspaceRequestSchema;
    output: typeof EditWorkspaceResponseSchema;
  },
  /**
   * @generated from rpc api.TenantService.GetUsers
   */
  getUsers: {
    methodKind: "unary";
    input: typeof GetUsersRequestSchema;
    output: typeof GetUsersResponseSchema;
  },
  /**
   * @generated from rpc api.TenantService.GetUserWorkspaceAssignment
   */
  getUserWorkspaceAssignment: {
    methodKind: "unary";
    input: typeof GetUserWorkspaceAssignmentRequestSchema;
    output: typeof GetUserWorkspaceAssignmentResponseSchema;
  },
  /**
   * @generated from rpc api.TenantService.AssignUserToWorkspace
   */
  assignUserToWorkspace: {
    methodKind: "unary";
    input: typeof AssignUserToWorkspaceRequestSchema;
    output: typeof AssignUserToWorkspaceResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_api_tenant, 0);

