// @generated by protoc-gen-connect-query v2.0.1 with parameter "target=ts"
// @generated from file api/tenant.proto (package api, syntax proto3)
/* eslint-disable */

import { TenantService } from "./tenant_pb";

/**
 * @generated from rpc api.TenantService.CreateWorkspace
 */
export const createWorkspace = TenantService.method.createWorkspace;

/**
 * @generated from rpc api.TenantService.GetWorkspaces
 */
export const getWorkspaces = TenantService.method.getWorkspaces;

/**
 * @generated from rpc api.TenantService.EditWorkspace
 */
export const editWorkspace = TenantService.method.editWorkspace;

/**
 * @generated from rpc api.TenantService.GetUsers
 */
export const getUsers = TenantService.method.getUsers;

/**
 * @generated from rpc api.TenantService.GetUserWorkspaceAssignment
 */
export const getUserWorkspaceAssignment = TenantService.method.getUserWorkspaceAssignment;

/**
 * @generated from rpc api.TenantService.AssignUserToWorkspace
 */
export const assignUserToWorkspace = TenantService.method.assignUserToWorkspace;
