// @generated by protoc-gen-connect-query v2.0.1 with parameter "target=ts"
// @generated from file api/tenantManagement.proto (package api, syntax proto3)
/* eslint-disable */

import { TenantManagementService } from "./tenantManagement_pb";

/**
 * @generated from rpc api.TenantManagementService.CreateWorkspace
 */
export const createWorkspace = TenantManagementService.method.createWorkspace;

/**
 * @generated from rpc api.TenantManagementService.GetWorkspaces
 */
export const getWorkspaces = TenantManagementService.method.getWorkspaces;

/**
 * @generated from rpc api.TenantManagementService.EditWorkspace
 */
export const editWorkspace = TenantManagementService.method.editWorkspace;
