kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-file-groups-iunvi-dev-eastus-001
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  volumeName: pv-file-groups-iunvi-dev-eastus-001
  storageClassName: azureblob-fuse-premium

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-file-groups-iunvi-dev-eastus-001
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  volumeName: pv-file-groups-iunvi-dev-eastus-001
  storageClassName: azureblob-nfs-premium

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-dashboards-iunvi-dev-eastus-001
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  volumeName: pv-dashboards-iunvi-dev-eastus-001
  storageClassName: azureblob-nfs-premium

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-model-runs-iunvi-dev-eastus-001
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  volumeName: pv-model-runs-iunvi-dev-eastus-001
  storageClassName: azureblob-nfs-premium

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-model-run-dashboards-iunvi-dev-eastus-001
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  volumeName: pv-model-run-dashboards-iunvi-dev-eastus-001
  storageClassName: azureblob-nfs-premium
