version: "3"

includes:
  client:
    taskfile: client/Client.yml
    dir: client
  tenant:
    taskfile: cmd/tenant/Tenant.yml
    dir: cmd/tenant
  file:
    taskfile: cmd/file/File.yml
    dir: cmd/file
  model:
    taskfile: cmd/model/Model.yml
    dir: cmd/model
  dashboard:
    taskfile: cmd/dashboard/Dashboard.yml
    dir: cmd/dashboard

tasks:
  generate:
    cmds:
      - buf generate
  run:
    deps:
      - client:run
      - tenant:run
      - file:run
      - model:run
      - dashboard:run
  live:
    deps:
      - client:run
      - tenant:live
      - file:live
      - model:live
      - dashboard:live
